package com.yizhiyun.dingcan.model;
// Generated Jun 11, 2014 11:44:43 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CustomerOrders generated by hbm2java
 */
public class CustomerOrder  implements java.io.Serializable {


     private long customerOrderId;
     private Integer customerOrderCustomerId;
     private String customerOrderCustomerAddress;
     private String customerOrderCustomerTel;
     private Character customerOrderStatus;
     private Date customerOrderTime;

    public CustomerOrder() {
    }

	
    public CustomerOrder(long customerOrderId) {
        this.customerOrderId = customerOrderId;
    }
    public CustomerOrder(long customerOrderId, Integer customerOrderCustomerId, String customerOrderCustomerAddress, String customerOrderCustomerTel, Character customerOrderStatus, Date customerOrderTime) {
       this.customerOrderId = customerOrderId;
       this.customerOrderCustomerId = customerOrderCustomerId;
       this.customerOrderCustomerAddress = customerOrderCustomerAddress;
       this.customerOrderCustomerTel = customerOrderCustomerTel;
       this.customerOrderStatus = customerOrderStatus;
       this.customerOrderTime = customerOrderTime;
    }
   
    public long getCustomerOrderId() {
        return this.customerOrderId;
    }
    
    public void setCustomerOrderId(long customerOrderId) {
        this.customerOrderId = customerOrderId;
    }
    public Integer getCustomerOrderCustomerId() {
        return this.customerOrderCustomerId;
    }
    
    public void setCustomerOrderCustomerId(Integer customerOrderCustomerId) {
        this.customerOrderCustomerId = customerOrderCustomerId;
    }
    public String getCustomerOrderCustomerAddress() {
        return this.customerOrderCustomerAddress;
    }
    
    public void setCustomerOrderCustomerAddress(String customerOrderCustomerAddress) {
        this.customerOrderCustomerAddress = customerOrderCustomerAddress;
    }
    public String getCustomerOrderCustomerTel() {
        return this.customerOrderCustomerTel;
    }
    
    public void setCustomerOrderCustomerTel(String customerOrderCustomerTel) {
        this.customerOrderCustomerTel = customerOrderCustomerTel;
    }
    public Character getCustomerOrderStatus() {
        return this.customerOrderStatus;
    }
    
    public void setCustomerOrderStatus(Character customerOrderStatus) {
        this.customerOrderStatus = customerOrderStatus;
    }
    public Date getCustomerOrderTime() {
        return this.customerOrderTime;
    }
    
    public void setCustomerOrderTime(Date customerOrderTime) {
        this.customerOrderTime = customerOrderTime;
    }




}


