package com.yizhiyun.dingcan.model;

// Generated Jun 11, 2014 11:44:43 PM by Hibernate Tools 3.6.0

import java.util.Date;

/**
 * Feedbacks generated by hbm2java
 */
public class Feedback {

	private long feedbackId;
	private Integer vendorId;
	private Integer customerId;
	private Date feedbackTime;
	private String feedbackContent;

	public Feedback() {
	}

	public Feedback(long feedbackId) {
		this.feedbackId = feedbackId;
	}

	public Feedback(long feedbackId, Integer vendorId, Integer customerId,
			Date feedbackTime, String feedbackContent) {
		this.feedbackId = feedbackId;
		this.vendorId = vendorId;
		this.customerId = customerId;
		this.feedbackTime = feedbackTime;
		this.feedbackContent = feedbackContent;
	}

	public long getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(long feedbackId) {
		this.feedbackId = feedbackId;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public Integer getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Date getFeedbackTime() {
		return this.feedbackTime;
	}

	public void setFeedbackTime(Date feedbackTime) {
		this.feedbackTime = feedbackTime;
	}

	public String getFeedbackContent() {
		return this.feedbackContent;
	}

	public void setFeedbackContent(String feedbackContent) {
		this.feedbackContent = feedbackContent;
	}

}
