package com.yizhiyun.dingcan.model;

// Generated Jun 11, 2014 11:44:43 PM by Hibernate Tools 3.6.0

/**
 * Food generated by hbm2java
 */
public class Food {

	private int foodId;
	private String foodName;
	private Float foodPrice;
	private Integer vendorId;
	private String foodStatus;

	public Food() {
	}

	public Food(int foodId) {
		this.foodId = foodId;
	}

	public Food(int foodId, String foodName, Float foodPrice, Integer vendorId,
			String foodStatus) {
		this.foodId = foodId;
		this.foodName = foodName;
		this.foodPrice = foodPrice;
		this.vendorId = vendorId;
		this.foodStatus = foodStatus;
	}

	public int getFoodId() {
		return this.foodId;
	}

	public void setFoodId(int foodId) {
		this.foodId = foodId;
	}

	public String getFoodName() {
		return this.foodName;
	}

	public void setFoodName(String foodName) {
		this.foodName = foodName;
	}

	public Float getFoodPrice() {
		return this.foodPrice;
	}

	public void setFoodPrice(Float foodPrice) {
		this.foodPrice = foodPrice;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public String getFoodStatus() {
		return this.foodStatus;
	}

	public void setFoodStatus(String foodStatus) {
		this.foodStatus = foodStatus;
	}

}
