package com.yizhiyun.dingcan;
// Generated Jun 11, 2014 11:44:43 PM by Hibernate Tools 3.6.0



/**
 * Customers generated by hbm2java
 */
public class Customers  implements java.io.Serializable {


     private int customerId;
     private String customerAddress;
     private String customerTel;//逻辑上是唯一标示符
     private String customerName;
     private String customerOptionalTel;
     private String customerOptionalTel2;
     private String customerOptionalTel3;

    public Customers() {
    }

	
    public Customers(int customerId) {
        this.customerId = customerId;
    }
    public Customers(int customerId, String customerAddress, String customerTel, String customerName, String customerOptionalTel, String customerOptionalTel2, String customerOptionalTel3) {
       this.customerId = customerId;
       this.customerAddress = customerAddress;
       this.customerTel = customerTel;
       this.customerName = customerName;
       this.customerOptionalTel = customerOptionalTel;
       this.customerOptionalTel2 = customerOptionalTel2;
       this.customerOptionalTel3 = customerOptionalTel3;
    }
   
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }
    public String getCustomerAddress() {
        return this.customerAddress;
    }
    
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }
    public String getCustomerTel() {
        return this.customerTel;
    }
    
    public void setCustomerTel(String customerTel) {
        this.customerTel = customerTel;
    }
    public String getCustomerName() {
        return this.customerName;
    }
    
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }
    public String getCustomerOptionalTel() {
        return this.customerOptionalTel;
    }
    
    public void setCustomerOptionalTel(String customerOptionalTel) {
        this.customerOptionalTel = customerOptionalTel;
    }
    public String getCustomerOptionalTel2() {
        return this.customerOptionalTel2;
    }
    
    public void setCustomerOptionalTel2(String customerOptionalTel2) {
        this.customerOptionalTel2 = customerOptionalTel2;
    }
    public String getCustomerOptionalTel3() {
        return this.customerOptionalTel3;
    }
    
    public void setCustomerOptionalTel3(String customerOptionalTel3) {
        this.customerOptionalTel3 = customerOptionalTel3;
    }




}


